export const USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS';
export const USER_DOES_NOT_EXIST = 'USER_DOES_NOT_EXIST';
export const INVALID_VALUE = 'INVALID_VALUE';
export const NOT_AUTHORIZED = 'NOT_AUTHORIZED';
export const NOT_FOUND = 'NOT_FOUND';
export const UNEXPECTED_ERROR = 'UNEXPECTED_ERROR';